language: r
cache: packages
latex: false
warnings_are_errors: false

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      before_script:
        - sudo sed -i '/<listen_host>::1/d' /etc/clickhouse-server/config.xml   # don't listen on localhost
        - sudo service clickhouse-server start    # not using builtin service directive, so that the steps are executed in the correct order
      addons:
        apt:
          packages:
            - clickhouse-server-base
            - clickhouse-server-common
          sources:
          - sourceline: 'deb http://repo.yandex.ru/clickhouse/trusty stable main'
    - os: osx
      osx_image: xcode9.2
      before_install:
        - brew tap hatarist/clickhouse
      install:
        - travis_wait 30 brew install clickhouse
      before_script:
        - brew services start clickhouse
